package com.cruise.forms.creator;

import java.util.ArrayList;

public class Access {
     ArrayList roles = new ArrayList();
     String type;
	public ArrayList getRoles() {
		return roles;
	}
	public void setRoles(ArrayList roles) {
		this.roles = roles;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
     
}
/**
{  
  "created":"2016-07-27T01:57:52.976Z",
  "revisions":"",
  "_vid":0,
  "_id":"57981520ff9b236800b09b31",
  "machineName":"pjmfogrfqptslvi:testForm",
  "modified":"2016-08-09T02:10:03.990Z",
  "title":"Test Form",
  "display":"form",
  "name":"testForm",
  "path":"test",
  "project":"579814a4ff9b236800b09b22"
  "type":"form",
  "tags":[  

  ],
  "access":[  
     {  
        "roles":[  
           "579814a4ff9b236800b09b23",
           "579814a4ff9b236800b09b24",
           "579814a5ff9b236800b09b25",
           "579f879d5b7a477b0026f821"
        ],
        "type":"read_all"
     }
  ],
  "submissionAccess":[  

  ],
  "owner":"553dbfc08d22d5cb1a7024f2",
  "components":[  
     {  
        "conditional":{  
           "eq":"",
           "when":Null,
           "show":""
        },
        "type":"columns",
        "columns":[  
           {  
              "components":[  
                 {  
                    "isNew":False,
                    "type":"textfield",
                    "conditional":{  
                       "eq":"",
                       "when":Null,
                       "show":""
                    },
                    "validate":{  
                       "customPrivate":False,
                       "custom":"",
                       "pattern":"",
                       "maxLength":"",
                       "minLength":"",
                       "required":False
                    },
                    "persistent":True,
                    "unique":False,
                    "protected":False,
                    "defaultValue":"",
                    "multiple":False,
                    "suffix":"",
                    "prefix":"",
                    "placeholder":"Enter your first name",
                    "key":"firstName",
                    "label":"First Name",
                    "inputMask":"",
                    "inputType":"text",
                    "tableView":True,
                    "input":True
                 },
                 {  
                    "conditional":{  
                       "eq":"",
                       "when":Null,
                       "show":""
                    },
                    "type":"email",
                    "persistent":True,
                    "unique":False,
                    "protected":False,
                    "defaultValue":"",
                    "suffix":"",
                    "prefix":"",
                    "placeholder":"Enter your email address",
                    "key":"email",
                    "label":"Email",
                    "inputType":"email",
                    "tableView":True,
                    "input":True
                 }
              ]
           },
           {  
              "components":[  
                 {  
                    "type":"textfield",
                    "conditional":{  
                       "eq":"",
                       "when":"",
                       "show":""
                    },
                    "validate":{  
                       "customPrivate":False,
                       "custom":"",
                       "pattern":"",
                       "maxLength":"",
                       "minLength":"",
                       "required":False
                    },
                    "persistent":True,
                    "unique":False,
                    "protected":False,
                    "defaultValue":"",
                    "multiple":False,
                    "suffix":"",
                    "prefix":"",
                    "placeholder":"Enter your last name",
                    "key":"lastName",
                    "label":"Last Name",
                    "inputMask":"",
                    "inputType":"text",
                    "tableView":True,
                    "input":True
                 },
                 {  
                    "lockKey":True,
                    "conditional":{  
                       "eq":"",
                       "when":Null,
                       "show":""
                    },
                    "type":"checkbox",
                    "validate":{  
                       "required":False
                    },
                    "persistent":True,
                    "protected":False,
                    "defaultValue":False,
                    "key":"havePhoneNumber",
                    "label":"Do you have a phone number?",
                    "hideLabel":True,
                    "tableView":True,
                    "inputType":"checkbox",
                    "input":True
                 },
                 {  
                    "conditional":{  
                       "eq":"true",
                       "when":"havePhoneNumber",
                       "show":"true"
                    },
                    "type":"phoneNumber",
                    "validate":{  
                       "required":False
                    },
                    "defaultValue":"",
                    "persistent":True,
                    "unique":False,
                    "protected":False,
                    "multiple":False,
                    "suffix":"",
                    "prefix":"",
                    "placeholder":"",
                    "key":"phoneNumber",
                    "label":"Phone Number",
                    "inputMask":"(999) 999-9999",
                    "tableView":True,
                    "input":True
                 }
              ]
           }
        ],
        "input":False
     },
     {  
        "type":"textfield",
        "conditional":{  
           "eq":"",
           "when":Null,
           "show":""
        },
        "validate":{  
           "customPrivate":False,
           "custom":"",
           "pattern":"",
           "maxLength":"",
           "minLength":"",
           "required":False
        },
        "persistent":True,
        "unique":False,
        "protected":False,
        "defaultValue":"",
        "multiple":True,
        "suffix":"",
        "prefix":"",
        "placeholder":"Enter your kids names",
        "key":"kids",
        "label":"Kids",
        "inputMask":"",
        "inputType":"text",
        "tableView":True,
        "input":True
     },
     {  
        "conditional":{  
           "eq":"",
           "when":Null,
           "show":""
        },
        "type":"datagrid",
        "persistent":True,
        "protected":False,
        "key":"cars",
        "label":"Cars",
        "tableView":True,
        "components":[  
           {  
              "hideLabel":True,
              "type":"textfield",
              "conditional":{  
                 "eq":"",
                 "when":Null,
                 "show":""
              },
              "validate":{  
                 "customPrivate":False,
                 "custom":"",
                 "pattern":"",
                 "maxLength":"",
                 "minLength":"",
                 "required":False
              },
              "persistent":True,
              "unique":False,
              "protected":False,
              "defaultValue":"",
              "multiple":False,
              "suffix":"",
              "prefix":"",
              "placeholder":"",
              "key":"make",
              "label":"Make",
              "inputMask":"",
              "inputType":"text",
              "tableView":True,
              "input":True
           },
           {  
              "hideLabel":True,
              "type":"textfield",
              "conditional":{  
                 "eq":"",
                 "when":Null,
                 "show":""
              },
              "validate":{  
                 "customPrivate":False,
                 "custom":"",
                 "pattern":"",
                 "maxLength":"",
                 "minLength":"",
                 "required":False
              },
              "persistent":True,
              "unique":False,
              "protected":False,
              "defaultValue":"",
              "multiple":False,
              "suffix":"",
              "prefix":"",
              "placeholder":"",
              "key":"model",
              "label":"Model",
              "inputMask":"",
              "inputType":"text",
              "tableView":True,
              "input":True
           },
           {  
              "hideLabel":True,
              "type":"textfield",
              "conditional":{  
                 "eq":"",
                 "when":Null,
                 "show":""
              },
              "validate":{  
                 "customPrivate":False,
                 "custom":"",
                 "pattern":"",
                 "maxLength":"",
                 "minLength":"",
                 "required":False
              },
              "persistent":True,
              "unique":False,
              "protected":False,
              "defaultValue":"",
              "multiple":False,
              "suffix":"",
              "prefix":"",
              "placeholder":"",
              "key":"year",
              "label":"Year",
              "inputMask":"",
              "inputType":"text",
              "tableView":True,
              "input":True
           }
        ],
        "tree":True,
        "input":True
     },
     {  
        "type":"button",
        "theme":"primary",
        "disableOnInvalid":True,
        "action":"submit",
        "block":False,
        "rightIcon":"",
        "leftIcon":"",
        "size":"md",
        "key":"submit",
        "tableView":False,
        "label":"Submit",
        "input":True
     }
  ]

}; 
*/

